import {
  AlertCircle,
  AlertOctagon,
  ArrowLeft,
  Bot,
  CheckCircle2,
  ChevronRight,
  FileCheck2,
  FileText,
  History,
  Info,
  Link2,
  LoaderCircle,
  LockKeyhole,
  RefreshCw,
  ShieldAlert,
  Sparkles,
  UserCheck,
} from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import type { AnalysisRun, AuditEvent, Citation, CorrectionInput, MaterialField, Requirement, TenderDetail } from '../types'
import { CorrectionDialog } from './CorrectionDialog'
import { StatusPill } from './StatusPill'

type Tab = 'overview' | 'evidence' | 'requirements' | 'activity'

const tabs: Array<{ id: Tab; label: string; icon: typeof FileText }> = [
  { id: 'overview', label: 'Overview', icon: FileText },
  { id: 'evidence', label: 'Evidence', icon: Link2 },
  { id: 'requirements', label: 'Requirements', icon: FileCheck2 },
  { id: 'activity', label: 'Activity', icon: History },
]

function formatDate(value?: string | null) {
  if (!value) return 'Not available'
  return new Intl.DateTimeFormat('en-CA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}

function requirementTone(status: Requirement['status']) {
  if (status === 'PASS') return 'positive' as const
  if (status === 'FAIL') return 'danger' as const
  if (status === 'REMEDIABLE') return 'warning' as const
  return 'neutral' as const
}

function humanStatus(run: AnalysisRun | null) {
  if (!run) return 'Not started'
  return run.status.charAt(0) + run.status.slice(1).toLowerCase()
}

function CitationList({ citations, onOpen }: { citations: Citation[]; onOpen?: () => void }) {
  if (citations.length === 0) return <span className="citation-empty">No source citation returned</span>
  return <div className="citation-list">{citations.map((citation, index) => <button type="button" className="citation-chip" onClick={onOpen} key={`${citation.line_start}-${index}`}><Link2 aria-hidden="true" />Lines {citation.line_start}–{citation.line_end}<span>{citation.quote}</span></button>)}</div>
}

function FieldCard({ field, model, definitionVersion, lastReviewed, onReview, onEvidence }: { field: MaterialField; model: string; definitionVersion: string; lastReviewed?: string; onReview: () => void; onEvidence: () => void }) {
  return (
    <article className="field-card">
      <header><div><p className="eyebrow">Material field</p><h3>{field.field_name.replaceAll('_', ' ')}</h3></div><StatusPill tone="warning">Needs human review</StatusPill></header>
      <p className="field-value">{String(field.value ?? 'Unknown')}</p>
      <dl className="transparency-grid">
        <div><dt>Why</dt><dd>Extracted as decision-relevant information from the cited source text.</dd></div>
        <div><dt>Evidence</dt><dd><CitationList citations={field.citations} onOpen={onEvidence} /></dd></div>
        <div><dt>Status</dt><dd>AI extracted · awaiting verification</dd></div>
        <div><dt>Generated by</dt><dd>Supervised tender analysis workflow</dd></div>
        <div><dt>Model / definition</dt><dd>{model} · {definitionVersion}</dd></div>
        <div><dt>Last reviewed</dt><dd>{lastReviewed ? formatDate(lastReviewed) : 'Not yet reviewed'}</dd></div>
      </dl>
      <button type="button" className="text-button" onClick={onReview}><UserCheck aria-hidden="true" />Review or correct<ChevronRight aria-hidden="true" /></button>
    </article>
  )
}

function RequirementCard({ item, onReview, onEvidence }: { item: Requirement; onReview: () => void; onEvidence: () => void }) {
  return (
    <article className={`requirement-card ${item.fatal && item.status !== 'PASS' ? 'requirement-card--fatal' : ''}`}>
      <header><div className="requirement-kicker"><span>{item.requirement_type === 'READINESS' ? 'Internal readiness check' : `${item.requirement_type.charAt(0)}${item.requirement_type.slice(1).toLowerCase()} criterion`}</span>{item.fatal ? <span className="fatal-label"><AlertOctagon />Fatal if unresolved</span> : null}</div><StatusPill tone={requirementTone(item.status)}>{item.status.charAt(0)}{item.status.slice(1).toLowerCase()}</StatusPill></header>
      <h3>{item.requirement}</h3>
      <p>{item.rationale}</p>
      {item.remediation ? <div className="remediation"><strong>Remediation</strong><span>{item.remediation}</span></div> : null}
      <CitationList citations={item.citations} onOpen={onEvidence} />
      <footer><span>{item.requirement_type === 'READINESS' ? 'Not a published tender requirement' : 'Source-backed tender requirement'}</span><button type="button" className="text-button" onClick={onReview}><UserCheck />Review<ChevronRight /></button></footer>
    </article>
  )
}

export function TenderWorkspace({ tenderId }: { tenderId: string }) {
  const [tender, setTender] = useState<TenderDetail | null>(null)
  const [run, setRun] = useState<AnalysisRun | null>(null)
  const [activity, setActivity] = useState<AuditEvent[]>([])
  const [tab, setTab] = useState<Tab>('overview')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [starting, setStarting] = useState(false)
  const [actionError, setActionError] = useState<string | null>(null)
  const [reviewTarget, setReviewTarget] = useState<{ path: string; value: unknown } | null>(null)
  const [recording, setRecording] = useState(false)

  const loadWorkspace = useCallback(async (signal?: AbortSignal) => {
    setLoading(true)
    setError(null)
    try {
      const [tenderResult, activityResult] = await Promise.all([
        api.getTender(tenderId, signal),
        api.listActivity(tenderId, signal),
      ])
      setTender(tenderResult)
      setActivity(activityResult.items)
      const storedRun = sessionStorage.getItem(`tender-run:${tenderId}`)
      const latestRunId = storedRun || tenderResult.latest_run_id
      if (latestRunId) setRun(await api.getAnalysisRun(latestRunId, signal))
    } catch (reason) {
      if ((reason as Error).name !== 'AbortError') setError(reason instanceof Error ? reason.message : 'Unable to load tender')
    } finally {
      setLoading(false)
    }
  }, [tenderId])

  useEffect(() => {
    const controller = new AbortController()
    void loadWorkspace(controller.signal)
    return () => controller.abort()
  }, [loadWorkspace])

  useEffect(() => {
    if (!run || !['QUEUED', 'RUNNING'].includes(run.status)) return
    const controller = new AbortController()
    const timer = window.setInterval(() => {
      api.getAnalysisRun(run.run_id, controller.signal)
        .then(setRun)
        .catch((reason: unknown) => { if ((reason as Error).name !== 'AbortError') setActionError(reason instanceof Error ? reason.message : 'Unable to refresh analysis') })
    }, 1500)
    return () => { controller.abort(); window.clearInterval(timer) }
  }, [run])

  const analysis = run?.analysis ?? null
  const sourceLines = useMemo(() => {
    if (!tender) return []
    const lines = tender.source_text.split(/\r\n|\n|\r/)
    if (lines.length > 1 && lines.at(-1) === '') lines.pop()
    return lines
  }, [tender])

  const startAnalysis = async () => {
    setStarting(true)
    setActionError(null)
    try {
      const started = await api.startAnalysis(tenderId)
      sessionStorage.setItem(`tender-run:${tenderId}`, started.run_id)
      setRun({ ...started, tender_id: tenderId, analysis: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() })
    } catch (reason) {
      setActionError(reason instanceof Error ? reason.message : 'Unable to start analysis')
    } finally {
      setStarting(false)
    }
  }

  const submitReview = async (value: { action: 'CORRECTION' | 'REVIEW'; reason: string; correctedValue?: string }) => {
    if (!reviewTarget) return
    setRecording(true)
    setActionError(null)
    const input: CorrectionInput = {
      actor_id: 'current-user',
      action: value.action,
      reason: value.reason,
      analysis_run_id: run?.run_id ?? null,
      field_path: reviewTarget.path,
      previous_value: reviewTarget.value,
      corrected_value: value.correctedValue,
    }
    try {
      const event = await api.submitCorrection(tenderId, input)
      setActivity((current) => [event, ...current])
      setReviewTarget(null)
    } catch (reason) {
      setActionError(reason instanceof Error ? reason.message : 'Unable to record review')
    } finally {
      setRecording(false)
    }
  }

  const showEvidence = () => setTab('evidence')

  if (loading) return <main id="main-content" className="page-shell"><div className="state-view page-state" aria-live="polite"><span className="spinner" /><strong>Opening tender workspace</strong><p>Loading source evidence and audit history.</p></div></main>
  if (error || !tender) return <main id="main-content" className="page-shell"><div className="state-view state-view--error page-state" role="alert"><AlertCircle /><strong>Tender workspace unavailable</strong><p>{error || 'The tender was not found.'}</p><button className="button button--secondary" onClick={() => void loadWorkspace()}>Try again</button><a className="text-link" href="/">Back to inbox</a></div></main>

  return (
    <main id="main-content" className="workspace-shell">
      <header className="workspace-header">
        <div className="workspace-breadcrumb"><a href="/"><ArrowLeft />Work inbox</a><span>/</span><span>{tender.solicitation_number || tender.reference_number || 'Tender'}</span></div>
        <div className="workspace-title-row">
          <div><div className="title-status"><StatusPill tone="info">Draft workspace</StatusPill><span className="solicitation">{tender.solicitation_number || 'No solicitation number'}</span></div><h1>{tender.title}</h1><p>{tender.buyer || 'Buyer pending extraction'} · Closing {formatDate(tender.deadline)}</p></div>
          <div className="workspace-actions"><div className="mode-lock"><LockKeyhole /><div><strong>Read-only &amp; draft-only</strong><span>No autonomous submission</span></div></div><button className="button button--primary" onClick={() => void startAnalysis()} disabled={starting || run?.status === 'QUEUED' || run?.status === 'RUNNING'}>{starting || run?.status === 'QUEUED' || run?.status === 'RUNNING' ? <LoaderCircle className="spin" /> : <Sparkles />}{starting ? 'Starting…' : run?.status === 'QUEUED' || run?.status === 'RUNNING' ? 'Analysis running' : analysis ? 'Run analysis again' : 'Start AI analysis'}</button></div>
        </div>
        {actionError ? <div className="inline-alert inline-alert--danger" role="alert"><AlertCircle />{actionError}<button type="button" onClick={() => setActionError(null)} aria-label="Dismiss error">×</button></div> : null}
        {run ? <div className="run-strip" aria-live="polite"><div><Bot /><span>Analysis run</span><strong>{humanStatus(run)}</strong></div><div className="run-progress"><span className={run.status === 'SUCCEEDED' ? 'complete' : ''} /><span className={run.status === 'RUNNING' || run.status === 'SUCCEEDED' ? 'complete' : ''} /><span className={run.status === 'SUCCEEDED' ? 'complete' : ''} /></div><span>Workflow {run.workflow_id}</span>{run.status === 'FAILED' ? <strong className="danger-text">{run.error_code || 'Analysis failed'}</strong> : null}</div> : null}
      </header>

      <div className="workspace-tabs" role="tablist" aria-label="Tender workspace sections">{tabs.map(({ id, label, icon: Icon }) => <button key={id} role="tab" aria-selected={tab === id} aria-controls={`${id}-panel`} id={`${id}-tab`} onClick={() => setTab(id)}><Icon />{label}{id === 'requirements' && analysis ? <span className="tab-count">{analysis.requirements.length}</span> : null}</button>)}</div>

      <section className="workspace-content" role="tabpanel" id={`${tab}-panel`} aria-labelledby={`${tab}-tab`}>
        {tab === 'overview' ? (
          <div className="overview-layout">
            {!analysis ? <div className="empty-analysis"><span><Sparkles /></span><h2>Ready for supervised analysis</h2><p>Start the workflow to extract material fields, find mandatory requirements, and generate a source-linked recommendation. A human must verify every consequential conclusion.</p><button className="button button--primary" onClick={() => void startAnalysis()} disabled={starting || run?.status === 'QUEUED' || run?.status === 'RUNNING'}><Sparkles />Start AI analysis</button></div> : (
              <>
                <section className="decision-card">
                  <div className="decision-primary"><p className="eyebrow">AI recommendation</p><div className="recommendation-line"><h2>{analysis.recommendation === 'INCLUDE' ? 'Include for bid review' : analysis.recommendation === 'EXCLUDE' ? 'Exclude from pipeline' : 'Human review required'}</h2><StatusPill tone={analysis.recommendation === 'INCLUDE' ? 'positive' : analysis.recommendation === 'EXCLUDE' ? 'danger' : 'warning'}>{analysis.recommendation}</StatusPill></div><p>{analysis.summary}</p><div className="confidence"><span>Confidence</span><div role="meter" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(analysis.confidence * 100)} aria-label="Analysis confidence"><i style={{ width: `${analysis.confidence * 100}%` }} /></div><strong>{Math.round(analysis.confidence * 100)}%</strong><small>Model confidence, not factual certainty</small></div></div>
                  <aside className={analysis.gate_outcome === 'BID_BLOCKED' ? 'gate-card gate-card--blocked' : 'gate-card gate-card--clear'}>{analysis.gate_outcome === 'BID_BLOCKED' ? <ShieldAlert /> : <CheckCircle2 />}<p className="eyebrow">Deterministic hard gate</p><h3>{analysis.gate_outcome === 'BID_BLOCKED' ? 'Bid blocked' : 'No fatal block found'}</h3>{analysis.gate_block_reasons.length ? <ul>{analysis.gate_block_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul> : <p>Eligibility still requires human compliance approval.</p>}</aside>
                </section>
                {analysis.missing_facts.length ? <section className="exception-panel"><header><AlertTriangleIcon /><div><h2>Missing facts need attention</h2><p>{analysis.missing_facts.length} unresolved item{analysis.missing_facts.length === 1 ? '' : 's'} can affect the decision.</p></div></header><ul>{analysis.missing_facts.map((item) => <li key={item.fact}><strong>{item.fact}</strong><span>{item.impact}</span></li>)}</ul></section> : null}
                <section><div className="section-heading"><div><p className="eyebrow">Transparent outputs</p><h2>Material fields</h2></div><span>{analysis.cited_material_fields.length} extracted</span></div>{analysis.cited_material_fields.length ? <div className="field-grid">{analysis.cited_material_fields.map((field) => { const fieldPath = `analysis.cited_material_fields.${field.field_name}`; return <FieldCard key={field.field_name} field={field} model={analysis.model} definitionVersion={analysis.definition_version} lastReviewed={activity.find((event) => event.field_path === fieldPath)?.occurred_at} onEvidence={showEvidence} onReview={() => setReviewTarget({ path: fieldPath, value: field.value })} /> })}</div> : <div className="compact-empty"><Info />No material fields were returned by this run.</div>}</section>
              </>
            )}
          </div>
        ) : null}

        {tab === 'evidence' ? <div className="evidence-layout"><section className="source-viewer"><header><div><p className="eyebrow">Immutable source snapshot</p><h2>Source text</h2><code className="source-hash" title={tender.source_sha256}>SHA-256 {tender.source_sha256}</code></div><StatusPill tone="info">{tender.line_count} lines</StatusPill></header><div className="source-scroll" tabIndex={0} aria-label="Line-addressable tender source">{sourceLines.map((line, index) => <div className="source-line" id={`line-${index + 1}`} key={index}><span aria-hidden="true">{index + 1}</span><code>{line || ' '}</code></div>)}</div><footer><LockKeyhole />Original source is read-only. Corrections are stored as separate audit events.</footer></section><aside className="evidence-index"><div className="section-heading"><div><p className="eyebrow">Citation index</p><h2>Analysis evidence</h2></div></div>{analysis?.cited_material_fields.length ? analysis.cited_material_fields.map((field) => <article key={field.field_name}><strong>{field.field_name.replaceAll('_', ' ')}</strong><span>{String(field.value)}</span><CitationList citations={field.citations} onOpen={() => document.getElementById(`line-${field.citations[0]?.line_start}`)?.scrollIntoView({ behavior: 'smooth' })} /></article>) : <div className="compact-empty"><Info />Run analysis to create line-level citations.</div>}</aside></div> : null}

        {tab === 'requirements' ? <div className="requirements-layout"><div className="section-heading"><div><p className="eyebrow">Compliance matrix</p><h2>Published requirements &amp; readiness</h2><p>Mandatory, rated, and internal readiness checks remain distinct.</p></div>{analysis ? <div className="requirement-summary"><span><strong>{analysis.requirements.filter((item) => item.status === 'FAIL').length}</strong> failed</span><span><strong>{analysis.requirements.filter((item) => item.status === 'UNKNOWN').length}</strong> unknown</span></div> : null}</div>{analysis?.requirements.length ? <div className="requirement-list">{analysis.requirements.map((item, index) => <RequirementCard key={`${item.requirement}-${index}`} item={item} onEvidence={showEvidence} onReview={() => setReviewTarget({ path: `analysis.requirements.${index}`, value: item.status })} />)}</div> : <div className="empty-analysis"><FileCheck2 /><h2>No compliance assessment yet</h2><p>Run analysis to identify source-backed mandatory and rated criteria.</p></div>}</div> : null}

        {tab === 'activity' ? <div className="activity-layout"><div className="section-heading"><div><p className="eyebrow">Append-only audit</p><h2>Activity timeline</h2><p>Human interventions, corrections, and workflow actions remain attributable.</p></div><button className="button button--secondary" onClick={() => void loadWorkspace()}><RefreshCw />Refresh</button></div>{activity.length ? <ol className="timeline">{activity.map((event) => <li key={event.id}><span className="timeline-icon">{event.action === 'CORRECTION' ? <FileCheck2 /> : <UserCheck />}</span><div><div><strong>{event.action === 'CORRECTION' ? 'Finding corrected' : event.action.replaceAll('_', ' ')}</strong><time dateTime={event.occurred_at}>{formatDate(event.occurred_at)}</time></div><p>{event.reason}</p><dl><div><dt>Actor</dt><dd>{event.actor_id}</dd></div><div><dt>Field</dt><dd>{event.field_path}</dd></div><div><dt>Correlation</dt><dd>{event.correlation_id}</dd></div></dl></div></li>)}</ol> : <div className="empty-analysis"><History /><h2>No recorded activity</h2><p>Reviews and corrections will appear here with actor, reason, and correlation ID.</p></div>}</div> : null}
      </section>

      <CorrectionDialog open={Boolean(reviewTarget)} fieldPath={reviewTarget?.path || ''} previousValue={reviewTarget?.value} submitting={recording} error={actionError} onClose={() => { setReviewTarget(null); setActionError(null) }} onSubmit={submitReview} />
    </main>
  )
}

function AlertTriangleIcon() {
  return <AlertCircle aria-hidden="true" />
}
